"use server";

import { openai } from "@ai-sdk/openai";
import {
  generateText,
  jsonSchema,
  stepCountIs,
  type StepResult,
  type ToolSet,
} from "ai";
import { experimental_createMCPClient } from "@ai-sdk/mcp";
import { AgentContext } from "@/lib/types";
import { jwtDecode } from "jwt-decode";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import { isJWT } from "@/lib/utils";
import crypto from "crypto";

// LangSmith's model-wrapper API (wrapAISDKModel) was removed in langsmith >=0.8
// in favor of wrapAISDK/telemetry, and no LangSmith credentials are configured,
// so the model is used directly. Re-introduce tracing via the new API if needed.
const modelWithTracing = openai("gpt-5.4");

interface FormattedStep {
  step: number;
  text: string;
  tool: string;
  input: unknown;
  result: unknown;
}

interface ToolCall {
  type: string;
  toolCallId: string;
  toolName: string;
  input: {
    [key: string]: string;
  };
}

interface ToolResult {
  result: {
    content: Array<{ type: string; text: string }>;
  };
}

interface DecodedJWTResult {
  token: string;
  jwtDecoded: unknown;
  isValidJWT: boolean;
  debug?: { responseSample: string };
}

function extractAccessTokenFromToolText(text: string): string {
  // Preferred: seller returns structured JSON (so we don't depend on prose formatting).
  try {
    const parsed = JSON.parse(text) as unknown;
    if (parsed && typeof parsed === "object") {
      const maybe = (parsed as { accessToken?: unknown }).accessToken;
      if (typeof maybe === "string" && maybe.length > 0) {
        return maybe;
      }
    }
  } catch {
    // Not JSON, fall back.
  }

  // Back-compat: allow prose responses.
  return extractJwtFromText(text);
}

function extractJwtFromText(text: string): string {
  const jwtMatch = text.match(
    /eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+/,
  );
  return (jwtMatch?.[0] || "").trim();
}

function tokenFingerprint(tokenLike: string): {
  sha256_12: string;
  parts: number[];
  length: number;
} {
  const token = tokenLike ?? "";
  const parts = token.split(".").map((p) => p.length);
  const sha256_12 = crypto
    .createHash("sha256")
    .update(token, "utf8")
    .digest("hex")
    .slice(0, 12);
  return {
    sha256_12,
    parts: parts.length === 3 ? parts : [],
    length: token.length,
  };
}

// Use the SDK's types directly
type AIStep = StepResult<ToolSet>;

const textConfig: { [key: string]: string } = {
  "find-sellers":
    "I will use Skyfire's find-sellers tool to find a seller for the requested data & retrieve the MCP server URL of the seller",
  "create-kya-token":
    "I will use Skyfire's create-kya-token tool to create a KYA token for myself",
  "create-pay-token":
    "I will use Skyfire's create-pay-token tool to create a PAY token for the dataset which is later used by receiver to claim payment",
  "create-account-and-login":
    "I will use Dappier's create-account-and-login tool to create account and login myself using the KYA token from Skyfire and a password generated by me",
  "search-dataset":
    "I will use Dappier's search-dataset tool to find the right dataset",
  "get-pricing":
    "I will use Dappier's get-pricing tool to get the price of dataset",
  "download-dataset":
    "I will use Dappier's download-dataset tool to pay Dappier and get the download URL of the data",
  "retrieve-file-content":
    "I will use Reporting's retrieve-file-content tool to get the data and create a brief summary",
  "upload-csv":
    "I will use Reporting's upload-csv tool to upload csv data to Google Sheets and create a chart",
  "connect-mcp-server-tool": "Installing MCP server",
};

const connectMcpServerTool = {
  "connect-mcp-server-tool": {
    description:
      "Connects to the seller MCP server URL. After calling this tool, stop agent execution immediately after.",
    inputSchema: jsonSchema({
      type: "object",
      properties: {
        mcpServerUrl: {
          type: "string",
          description: "URL for seller MCP server",
        },
        sellerName: {
          type: "string",
          description: "Name of the seller",
        },
      },
      required: ["mcpServerUrl", "sellerName"],
      additionalProperties: false,
    }),
    execute: async ({
      mcpServerUrl,
      sellerName,
    }: {
      mcpServerUrl: string;
      sellerName: string;
    }) => {
      return {
        content: [
          {
            type: "text",
            text: `Connecting to ${sellerName} MCP server from ${mcpServerUrl}. Stopping and restarting agent to connect to tools provided by the seller.`,
          },
        ],
      };
    },
  },
};

export async function getAgent(
  apiKey: string,
  input: string | Record<string, string>,
  agentContext: AgentContext,
) {
  if (!apiKey) apiKey = process.env.SKYFIRE_API_KEY || "";

  // set default agent context having SKYFIRE and VISUALIZATION MCP servers
  if (!agentContext || Object.keys(agentContext).length === 0) {
    agentContext = {
      available_mcp_servers: [
        {
          url: process.env.SKYFIRE_MCP_URL || "",
          headers: {
            "skyfire-api-key": apiKey,
          },
        },
        { url: process.env.REPORTING_MCP_URL || "", headers: {} },
      ],
      dynamically_mounted_server: [],
      conversation_history: [
        {
          role: "system",
          content:
            "You are an e-commerce buyer agent assisting user to make a purchase. When connect-mcp-server-tool tool is executed, you must stop agent execution immediately-- there should be no subsequent tools executed. Whenever there is a need to create an account, use 123456S$d#d as the password. Do not truncate or mutate tokens. Use the okta auth0 version of the service.",
          // For the scope of this demo, the agent is instructed to use a static password for account creation and login. As an improvisation in future, the agent could randomly generate a password and store in agent memory and also share it with human using secure password services like 1Password, Keeper etc.
        },
      ],
    };
  }

  const inputObject: Record<string, string> =
    typeof input === "string" ? JSON.parse(input) : input;

  return runAgent(apiKey, inputObject.prompt, agentContext);
}

async function runAgent(
  apiKey: string,
  input: string,
  agentContext: AgentContext,
  initialFormattedSteps: FormattedStep[] = [],
) {
  // Prepare tools from all the connected MCP servers
  // eslint-disable-next-line prefer-const
  let allTools = await prepareAllTools(agentContext);

  // add user prompt to agentContext
  agentContext.conversation_history.push({
    role: "user",
    content: input,
  });

  // AI SDK v5+ no longer accepts `system`-role entries inside `messages`; they
  // must be supplied via the top-level `system` option. The agent accumulates
  // system entries (base instructions, MCP resource docs, "now connected"
  // notices) in conversation_history, so split them out at this boundary.
  const systemPrompt = agentContext.conversation_history
    .filter((m) => m.role === "system")
    .map((m) => (typeof m.content === "string" ? m.content : ""))
    .join("\n\n");
  const nonSystemMessages = agentContext.conversation_history.filter(
    (m) => m.role !== "system",
  );

  // Run agent by passing all the prepared tools and agentContext
  const {
    text: answer,
    usage,
    steps,
    response,
  } = await generateText({
    model: modelWithTracing,
    system: systemPrompt,
    maxOutputTokens: 8000,
    tools: allTools,
    stopWhen: stepCountIs(20),
    messages: nonSystemMessages,
  });

  // Update agentContext to include all the executed steps
  agentContext.conversation_history.push(...response.messages);

  // Format steps for display
  let formattedSteps: FormattedStep[] = [...initialFormattedSteps];

  formatOutput(steps, formattedSteps);

  // when MCP server is discovered, newToolsFound is set to True
  const newToolsFound = checkAndUpdateAgentContextIfMCPConnectionIsInitiated(
    steps,
    agentContext,
  );

  // If new tools are discovered, RE-RUN the agent
  if (newToolsFound) {
    const modelResponse = JSON.parse(
      await runAgent(apiKey, input, agentContext, formattedSteps),
    );
    formattedSteps = modelResponse.steps;
  }

  // Return final response
  // AI SDK v5+ renamed usage fields (inputTokens/outputTokens); the UI still
  // reads the legacy promptTokens/completionTokens shape, so map back here.
  return JSON.stringify(
    {
      answer,
      steps: formattedSteps,
      usage: {
        promptTokens: usage.inputTokens ?? 0,
        completionTokens: usage.outputTokens ?? 0,
        totalTokens: usage.totalTokens ?? 0,
      },
      agentContext,
    },
    null,
    2,
  );
}

const getDecodedJWT = (toolResult: ToolResult): DecodedJWTResult => {
  const tokenRes: string = toolResult.result.content[0]?.text || "";

  // Tokens in tool responses are human-readable strings like:
  // "Account created. Access token is <JWT>".
  // Don't rely on "last space-separated word" because the token may be followed by punctuation.
  const token: string = extractAccessTokenFromToolText(tokenRes);
  if (isJWT(token)) {
    const jwtHeader: string = jwtDecode(token, { header: true });
    const jwtPayload: string = jwtDecode(token);

    const jwtDecoded = { header: jwtHeader, payload: jwtPayload };
    return { token: token, jwtDecoded: jwtDecoded, isValidJWT: true };
  }

  // Fall back to returning something useful for debugging.
  // If we couldn't find a JWT-shaped substring, include a small sample of the response.
  return {
    token,
    jwtDecoded: {},
    isValidJWT: false,
    debug: { responseSample: tokenRes.slice(0, 200) },
  };
};

const pushFormattedSteps = (
  formattedSteps: FormattedStep[],
  token: string,
  jwtDecoded: { header: string; payload: string },
) => {
  return formattedSteps.push({
    step: 1,
    text: "Decoding JWT token...",
    tool: "thinking",
    input: {},
    result: {
      args: { token: token },
      result: { content: jwtDecoded },
    },
  });
};

const getStepDescription = (step: AIStep, toolCall: ToolCall | null) => {
  let text = step.text;
  if (toolCall) {
    text = textConfig[toolCall.toolName] || text;
    if (toolCall.toolName === "get-pricing") {
      text = text + " " + toolCall.input["datasetId"];
    }
  }
  return text;
};

function makeTransport(url: string, headers: Record<string, string>) {
  return new StreamableHTTPClientTransport(new URL(url), {
    requestInit: { headers },
  });
}

const prepareAllTools = async (agentContext: AgentContext) => {
  const clients: Record<string, unknown> = {};

  const allServers = [
    ...(agentContext?.available_mcp_servers ?? []),
    ...(agentContext?.dynamically_mounted_server ?? []),
  ];
  let allTools: ToolSet = { ...connectMcpServerTool } as ToolSet;

  //process mcp servers (tools + resources)
  for (let i = 0; i < allServers?.length; i++) {
    const server = allServers[i];
    const localVar = "client" + i;

    try {
      // ---- TOOLS CLIENT ----
      const toolsTransport = makeTransport(server.url, server.headers);
      const toolClient = await experimental_createMCPClient({
        transport: toolsTransport,
      });
      clients[localVar] = toolClient;

      const toolSet = await toolClient.tools();
      // Logging-only wrappers to prove whether the model is reusing a stale access token.
      // These wrappers DO NOT modify args.
      const wrappedToolSet: Record<string, unknown> = { ...toolSet };
      const wrapTool = (toolName: string) => {
        const orig = (wrappedToolSet as Record<string, unknown>)[toolName] as {
          execute?: (...args: unknown[]) => Promise<unknown>;
        };

        if (!orig?.execute) {
          return;
        }

        const execute = orig.execute;

        (wrappedToolSet as Record<string, unknown>)[toolName] = {
          ...(orig as Record<string, unknown>),
          // AI SDK v5+ calls execute(input, options); forward every argument
          // through so the underlying MCP tool keeps its abort signal / metadata.
          execute: async (...allArgs: unknown[]) => {
            const castedArgs = (allArgs[0] ?? {}) as Record<string, unknown>;
            const accessToken =
              typeof castedArgs.accessToken === "string"
                ? (castedArgs.accessToken as string)
                : "";
            const extracted = accessToken
              ? extractJwtFromText(accessToken)
              : "";

            const fp = extracted ? tokenFingerprint(extracted) : null;
            console.warn(
              `[buyer-token-proof] ${toolName} accessToken fingerprint:`,
              fp,
            );

            return execute(...allArgs);
          },
        };
      };

      wrapTool("create-account-and-login");
      wrapTool("search-dataset");
      wrapTool("get-pricing");
      wrapTool("download-dataset");

      allTools = { ...allTools, ...wrappedToolSet } as ToolSet;

      // ---- RESOURCES CLIENT ----
      const resourceTransport = makeTransport(server.url, server.headers);
      const mcpClient = new Client({
        name: "mcp-client",
        version: "1.0.0",
      });
      await mcpClient.connect(resourceTransport);

      const resources = await mcpClient.listResources().catch(() => null);
      if (!resources?.resources?.length) {
        console.warn(`${server.url} has no resources (skipping).`);
        continue;
      }

      for (const res of resources.resources) {
        const resource = await mcpClient.readResource({ uri: res.uri });
        console.log(
          `Resource loaded from ${server.url}:\n`,
          resource.contents[0].text,
        );

        agentContext.conversation_history.push({
          role: "system",
          content: `${resource.contents[0].text}`,
        });
      }
    } catch (err) {
      const errObj = err as Record<string, unknown>;
      const details: Record<string, unknown> = {
        message: errObj?.message ?? String(err),
        stack: errObj?.stack,
        code: errObj?.code,
        statusCode: errObj?.statusCode ?? errObj?.status,
        responseBody: errObj?.responseBody ?? errObj?.body,
        cause: errObj?.cause,
      };
      // Strip undefined fields for cleaner output
      Object.keys(details).forEach(
        (k) => details[k] === undefined && delete details[k],
      );
      console.error(
        `Unexpected error accessing resources for ${server.url}:`,
        details,
      );
    }
  }
  return allTools;
};

const formatOutput = (steps: AIStep[], formattedSteps: FormattedStep[]) => {
  steps.forEach((step: AIStep) => {
    if (step.toolCalls.length > 0) {
      for (let i = 0; i < step.toolCalls.length; i++) {
        const toolCall = step.toolCalls[i] as unknown as ToolCall;
        // AI SDK v5+ splits the old tool-result object into `.input` (the call
        // args) and `.output` (the payload). The UI renders step.result.args as
        // the "Request" and step.result.result.content as the "Response", so
        // re-assemble the legacy `{ args, result }` shape here. `toolResult`
        // (the `{ result }` half) is what the JWT decoder consumes.
        const rawToolResult = step.toolResults[i] as unknown as {
          output?: { content: Array<{ type: string; text: string }> };
        };
        const toolResult: ToolResult | null = rawToolResult?.output
          ? { result: rawToolResult.output }
          : null;
        formattedSteps.push({
          step: 1,
          text: getStepDescription(step, toolCall),
          tool: toolCall && toolCall.toolName ? toolCall.toolName : "thinking",
          input: toolCall ? toolCall.input : {},
          result: toolResult
            ? { args: toolCall?.input ?? {}, result: toolResult.result }
            : null,
        });

        if (
          toolCall &&
          toolResult &&
          (toolCall.toolName === "create-payment-token" ||
            toolCall.toolName === "create-kya-token" ||
            toolCall.toolName === "create-pay-token" ||
            toolCall.toolName === "create-account-and-login")
        ) {
          try {
            const { token, jwtDecoded, isValidJWT } = getDecodedJWT(toolResult);
            if (isValidJWT) {
              pushFormattedSteps(
                formattedSteps,
                token,
                JSON.parse(JSON.stringify(jwtDecoded)),
              );
            }
          } catch (err) {
            console.error("Error while decoding JWT token: ", err);
          }
        }
      }
    } else {
      formattedSteps.push({
        step: 1,
        text: getStepDescription(step, null),
        tool: "thinking",
        input: {},
        result: null,
      });
    }
  });
};

const checkAndUpdateAgentContextIfMCPConnectionIsInitiated = (
  steps: AIStep[],
  agentContext: AgentContext,
) => {
  let newToolsFound = false;

  steps.forEach((step: AIStep) => {
    const toolCall = step.toolCalls?.[0] as unknown as ToolCall;

    if (toolCall && toolCall.toolName === "connect-mcp-server-tool") {
      const url = toolCall.input["mcpServerUrl"];

      agentContext.dynamically_mounted_server = [{ url: url, headers: {} }];

      agentContext.conversation_history.push({
        role: "system",
        content:
          "You are now connected to the tools provided by the seller MCP server as well, run tools as per input prompt to solve problems step by step.",
      });

      newToolsFound = true;
      return;
    }
  });

  return newToolsFound;
};
